<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-OOQ7SLD" failures="0" tests="1" name="com.test.ExceptionTimeOutTest" time="2.017" errors="1" timestamp="10 Jul 2018 02:38:22 GMT" skipped="0">
  <testcase classname="com.test.ExceptionTimeOutTest" name="infinitloopTest" time="2.017">
    <error message="Method com.test.ExceptionTimeOutTest.infinitloopTest() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.test.ExceptionTimeOutTest.infinitloopTest() didn't finish within the time-out 2000
at java.base@9.0.1/java.io.FileOutputStream.writeBytes(Native Method)
at java.base@9.0.1/java.io.FileOutputStream.write(Unknown Source)
at java.base@9.0.1/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
at java.base@9.0.1/java.io.BufferedOutputStream.flush(Unknown Source)
at java.base@9.0.1/java.io.PrintStream.write(Unknown Source)
at java.base@9.0.1/sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
at java.base@9.0.1/sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
at java.base@9.0.1/sun.nio.cs.StreamEncoder.flushBuffer(Unknown Source)
at java.base@9.0.1/java.io.OutputStreamWriter.flushBuffer(Unknown Source)
at java.base@9.0.1/java.io.PrintStream.write(Unknown Source)
at java.base@9.0.1/java.io.PrintStream.print(Unknown Source)
at java.base@9.0.1/java.io.PrintStream.println(Unknown Source)
at app//com.test.ExceptionTimeOutTest.infinitloopTest(ExceptionTimeOutTest.java:11)
at java.base@9.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@9.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base@9.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base@9.0.1/java.lang.reflect.Method.invoke(Unknown Source)
at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.base@9.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.base@9.0.1/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base@9.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base@9.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base@9.0.1/java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- infinitloopTest -->
</testsuite> <!-- com.test.ExceptionTimeOutTest -->
